# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e3163a6b00f2a7719cb18eeb21ed6a1adb538133ad05984583107dab6eff81f9676feee9e1f49d7564a0d8841881073261ebc8dea3657db358bf6960b8e4937

test:
  secret_key_base: 03e64a414e83e1ac4042209261fdfb4fd3ded02de6b73771752591106677c5625e0cec7ee5a07b586e35d66aae1ce566c07c32862886797eeff1c8f4febe93b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
